begin;

create table if not exists public.api_usage_metrics (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  conversation_id uuid references public.bba_conversations(id) on delete set null,
  operation text not null default 'rag' check (operation in ('rag')),
  status text not null check (status in ('success', 'no_source', 'error', 'timeout', 'cancelled')),
  duration_ms integer not null check (duration_ms >= 0),
  source_count integer not null default 0 check (source_count >= 0),
  prompt_tokens integer not null default 0 check (prompt_tokens >= 0),
  completion_tokens integer not null default 0 check (completion_tokens >= 0),
  embedding_tokens integer not null default 0 check (embedding_tokens >= 0),
  estimated_cost_usd numeric(14,8) not null default 0 check (estimated_cost_usd >= 0),
  chat_model text,
  embedding_model text,
  error_code text,
  created_at timestamptz not null default now()
);

create index if not exists api_usage_metrics_created_at_idx on public.api_usage_metrics (created_at desc);
create index if not exists api_usage_metrics_status_created_at_idx on public.api_usage_metrics (status, created_at desc);
create index if not exists api_usage_metrics_user_created_at_idx on public.api_usage_metrics (auth_user_id, created_at desc);

alter table public.api_usage_metrics enable row level security;
alter table public.api_usage_metrics force row level security;
revoke all on table public.api_usage_metrics from anon, authenticated;
revoke all on sequence public.api_usage_metrics_id_seq from anon, authenticated;

comment on table public.api_usage_metrics is
  'Privacy-preserving RAG telemetry. Raw user questions and assistant answers are never stored here.';

commit;
